### ISSUE TITLE
Error trying to download Phantasy Star Online for Dreamcast

### ISSUE THREAD

**Issue by dbedrenko** [deltaclock/emu-paradise-download#2]
Hey, thanks for writing this excellent tool. Unfortunately, I am unable to download this game:

https://www.emuparadise.me/Sega_Dreamcast_ISOs/Phantasy_Star_Online_Ver._2_(Europe)(En,Fr,De,Es,Jp)/182485

Specifically the "Schthack" download of size "510M". I was hoping your tool would be able to do it, because the Greasemonkey script for EmuParadise also does not work.

Here is the full output:

```
[I][~/Programs/emu-paradise-download]$ ./emuDl.py                                                                                                                                                                                   *[master]
[+] Welcome to EmuParadise Downloader!
[+] Here is the list of currently supported platforms
-----------------------------------------------------
[0] Nintendo Game Boy Color
[1] PS2
[2] Nintendo Game Boy
[3] Nintendo Wii U
[4] Nintendo 64
[5] NES
[6] Nintendo DS
[7] ALL
[8] Nintendo Gameboy Advance
[9] XBox
[10] Sony Playstation
[11] SNES
[12] Nintendo Gamecube
[13] PSP
-----------------------------------------------------
Enter a console number: 7
[+] OK! Now type the game you wanna search for
Enter the game name: Phantasy Star Online
-----------------------------------------------------
[0] Phantasy Star Universe (USA) ISO - Size: 3.2G
[1] Phantasy Star Online Episode 3 Card Revolution ISO - Size: 1.1G
[2] Phantasy Star Online Episode 1 & 2 ISO - Size: 928M
[3] Phantasy Star Online Episodes 1 and 2 Plus ISO - Size: 924M
[4] Phantasy Star Portable 2 (USA) ISO - Size: 817M
[5] Phantasy Star Online Episode I & II (Europe) (En,Ja,Fr,De,Es) ISO - Size: 913M
[6] Phantasy Star Online Ver. 2 (Japan)(En,Fr,De,Es,Jp) ISO - Size: 735M
[7] Phantasy Star Online Episode I & II (En,Ja,Fr,De,Es) (v1.01) ISO - Size: 928M
[8] Phantasy Star Online Ver. 2 (Europe)(En,Fr,De,Es,Jp) ISO - Size: Size:
[9] Phantasy Star Portable 2 (Europe) ISO - Size: 817M
[10] Phantasy Star Portable 2 (Japan) ISO - Size: 1.4G
[11] Homeland (NTSC-J) ISO - Size: 398M
[12] Phantasy Star Online (USA)(En,Fr,De,Es,Jp) ISO - Size: 462M
[13] Phantasy Star Online Ver. 2 (USA)(En,Fr,De,Es,Jp) ISO - Size: 420M
[14] Phantasy Star Online (Europe)(En,Fr,De,Es,Jp) ISO - Size: 493M
[15] Phantasy Star Online (Japan)(En,Fr,De,Es,Jp) ISO - Size: 692M
-----------------------------------------------------
[+] Which of these games you want to download?
Enter the game number: 8
Traceback (most recent call last):
  File "./emuDl.py", line 207, in <module>
    gameDlUrl = main()
  File "./emuDl.py", line 189, in main
    gameDownloadLink, gameSize = parseGameLink(gamePageHtml)
  File "./emuDl.py", line 98, in parseGameLink
    downloadLink = 'http://direct.emuparadise.me' + downloadLink[0].get('href')
IndexError: list index out of range
```

**Comment by deltaclock** [comment]
Thanks for bringing this to my attention, i will post a fix in a bit.

**Comment by deltaclock** [comment]
@dbedrenko test if you have problems on the latest version. Needs python3

**Comment by dbedrenko** [comment]
Brilliant! I got the files. Thank you very much for the fix
