### ISSUE TITLE
Error on trying to download "Next Tetris On-line Edition"

### ISSUE THREAD

**Issue by dbedrenko** [deltaclock/emu-paradise-download#4]
Here is [another game](https://www.emuparadise.me/Sega_Dreamcast_ISOs/Next_Tetris,_The_-_On-line_Edition_(USA)/113) that throws an error when trying to download it. This is with the latest version of the script, with the recent Dreamcast fix included.

Notice that the script also identifies the wrong size (21MB instead of 349MB) and it only sees 1 download, when in fact there are 2 downloads: the 349MB .cdi and 390MB .gdi.

```
[I][~/Programs/emu-paradise-download]$ ./emuDl.py                                                            [master]
[+] Welcome to EmuParadise Downloader!
[+] Here is the list of currently supported platforms
-----------------------------------------------------
[0] ALL
[1] PS2
[2] PSP
[3] Nintendo 64
[4] Nintendo DS
[5] NES
[6] Sony Playstation
[7] SNES
[8] Nintendo Game Boy
[9] Nintendo Game Boy Color
[10] Nintendo Gameboy Advance
[11] Nintendo Gamecube
[12] XBox
[13] Nintendo Wii U
[14] Sega Dreamcast
-----------------------------------------------------
Enter a console number: 14
[+] OK! Now type the game you wanna search for
Enter the game name: tetris
-----------------------------------------------------
[0] Next Tetris, The - On-line Edition (USA) ISO - Size: 27M
[1] Next Tetris, The (United Kingdom) ISO - Size: 75M
[2] Tetris 4D (Japan) ISO - Size: 159M
[3] Sega Tetris (Japan) ISO - Size: Size:
-----------------------------------------------------
[+] Which of these games you want to download?
Enter the game number: 0
Traceback (most recent call last):
  File "./emuDl.py", line 245, in <module>
    links = main()
  File "./emuDl.py", line 220, in main
    download_links = get_direct_download_links(path)
  File "./emuDl.py", line 158, in get_direct_download_links
    for file in get_dreamcast_filenames(main_domain + game_path)
  File "./emuDl.py", line 157, in <listcomp>
    return [file_server_domain + "Dreamcast/" + file
  File "./emuDl.py", line 146, in get_dreamcast_filenames
    filename = re.match(regex, link.get('title')).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by deltaclock** [comment]
@dbedrenko verify also this

**Comment by dbedrenko** [comment]
The correct file now downoads, thank you :)
