### ISSUE TITLE
Unable to download Dreamcast games

### ISSUE THREAD

**Issue by JarHead4** [deltaclock/emu-paradise-download#6]
When I try to download any Dreamcast games I get an error and emuDL closes. I've tried downloading Sega GT, Daytona USA and POD Speedzone.

[+] Welcome to EmuParadise Downloader!
[+] Here is the list of currently supported platforms

[0] ALL
[1] PS2
[2] PSP
[3] Nintendo 64
[4] Nintendo DS
[5] NES
[6] Sony Playstation
[7] SNES
[8] Nintendo Game Boy
[9] Nintendo Game Boy Color
[10] Nintendo Gameboy Advance
[11] Nintendo Gamecube
[12] XBox
[13] Nintendo Wii U
[14] Sega Dreamcast
[15] PSX for PSP

Enter a console number: 14
[+] OK! Now type the game you wanna search for
Enter the game name: Sega GT

[0] Sega GT (USA) ISO - Size: 158M
[1] Sega GT (Europe)(En,Fr,De,Es) ISO - Size: 221M
[2] Sega GT - Homologation Special (Japan) ISO - Size: 827M
[3] Aqua GT (Europe)(En,Fr,De) ISO - Size: 80M

[+] Which of these games you want to download?
Enter the game number: 0
[*] Please wait..
Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 156, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 84, in create_connection
  File "site-packages\urllib3\util\connection.py", line 74, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 665, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 387, in _make_request
  File "http\client.py", line 1230, in request
  File "http\client.py", line 1276, in _send_request
  File "http\client.py", line 1225, in endheaders
  File "http\client.py", line 1004, in _send_output
  File "http\client.py", line 944, in send
  File "site-packages\urllib3\connection.py", line 184, in connect
  File "site-packages\urllib3\connection.py", line 168, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000168FBF3D1C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 439, in send
  File "site-packages\urllib3\connectionpool.py", line 719, in urlopen
  File "site-packages\urllib3\util\retry.py", line 436, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='50.7.92.186', port=80): Max retries exceeded with url: /happyxhJ1ACmlTrxJQpol71nBc/Dreamcast/Sega%20GT%20(USA)%5BDCRES%5D.7z (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168FBF3D1C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emuDl.py", line 408, in <module>
  File "emuDl.py", line 362, in main
  File "emuDl.py", line 239, in find_game_files
  File "emuDl.py", line 200, in __get_url_fileinfo
  File "site-packages\requests\api.py", line 101, in head
  File "site-packages\requests\api.py", line 60, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='50.7.92.186', port=80): Max retries exceeded with url: /happyxhJ1ACmlTrxJQpol71nBc/Dreamcast/Sega%20GT%20(USA)%5BDCRES%5D.7z (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000168FBF3D1C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
[5716] Failed to execute script emuDl

**Comment by deltaclock** [comment]
Seems like i fixed it, for some reason the old server i was using went down.
Re download the latest version and check again if it works for you.
```
$ python emuDl.py 
[+] Welcome to EmuParadise Downloader!
[+] Here is the list of currently supported platforms
-----------------------------------------------------
[0] ALL
[1] PS2
[2] PSP
[3] Nintendo 64
[4] Nintendo DS
[5] NES
[6] Sony Playstation
[7] SNES
[8] Nintendo Game Boy
[9] Nintendo Game Boy Color
[10] Nintendo Gameboy Advance
[11] Nintendo Gamecube
[12] XBox
[13] Nintendo Wii U
[14] Sega Dreamcast
[15] PSX for PSP
-----------------------------------------------------
Enter a console number: 14
[+] OK! Now type the game you wanna search for
Enter the game name: Daytona
-----------------------------------------------------
[0] Daytona USA (USA) ISO - Size: 423M
[1] Daytona USA 2001 (Europe)(En,Fr,De,Es) ISO - Size: 425M
[2] Daytona USA 2001 (Japan) ISO - Size: 495M
-----------------------------------------------------
[+] Which of these games you want to download?
Enter the game number: 0
[*] Please wait..
-----------------------------------------------------
[0] Daytona USA (USA)[DCCM] - Size: 327.1MiB - Available: ✔
[1] Daytona USA (USA) - Size: 491.8MiB - Available: ✔
[2] ALL
-----------------------------------------------------
[+] Which of these game files you want to download?
Enter the game file number/s (Comma separated): 1
Do you really want to download them? [y/n] y
[+] OK! Please wait while your game is downloading!
492MB [00:57, 9.00MB/s]                                                                                                                                                                        
Daytona USA (USA): ✔
[+] Games Downloaded! Have Fun!
```

**Comment by JarHead4** [comment]
Yep it works for me too. Thanks!
